### ISSUE TITLE
Exercises with non-standard error indicators

### ISSUE THREAD

**Issue by Insti** [exercism/problem-specifications#1311]
There are several exercises with non-standard error indicators.

The [canonical data documentation says](https://github.com/exercism/problem-specifications#test-data-format-canonical-datajson)

> If an error is expected (because the input is invalid, or any other reason), the value at "expected" should be an object containing exactly one property, "error", whose value is a string. 

I started creating issues for these but found there were a few more, so I've grouped them all together here.

**Todo:**

Update the `canonical-data.json` for each exercise to use the correct error format.

Exercises:
- [ ] grains   (Issue: #1309  PR: )
- [ ] largest-series-product    (Issue: #1310  PR:)
- [ ] ocr-numbers (PR: )
- [ ] phone-number (PR: )
- [ ] wordy (PR: )
- [ ] queen-attack (PR: )

See also: [hamming canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/hamming/canonical-data.json) for another example of how to do things the right way.

**Comment by petertseng** [comment]
Anything in https://github.com/petertseng/exercism-problem-specifications that has to pass a custom `error` to `verify` must be using a non-standard error (Since the default `error` is the standard).

So, that'd be:

```
$ git grep 'error: ->' | cut -d/ -f2            (08-30 19:35)
binary
change
forth
grains
largest-series-product
ocr-numbers
pascals-triangle
rna-transcription
say
trinary
variable-length-quantity
wordy
```

Note that that is a *sufficient* condition but not a *necessary* condition, so the omission of any exercise in this list does not give it a free pass (particularly, please still do pay attention to phone-number and queen-attack even though they are not in my list but are in the list in the issue description)

**Comment by petertseng** [comment]
I strike `rna-transcription` from my list; it apparently doesn't do errors anymore.

**Comment by rpottsoh** [comment]
Is #902 worth considering again?  Do all these exercises need to be testing for invalid input?  Is looking for invalid input germane to the exercise, if not can those cases be removed?

**Comment by Insti** [comment]
@petertseng nice, you've picked up some I didn't find (probably because the Ruby track doesn't have generators for them.)

@rpottsoh probably. I'm strongly in favor of removing invalid input related tests.

**Comment by petertseng** [comment]
One may wish to discuss `binary-search` which uses `-1` to signal "searched-for item is not in array", and ask whether that is a non-standard error indicator. I don't consider searching for an nonexistent item an error, so I would oppose changing this to use the `error` object.

**Comment by petertseng** [comment]
EBWODP: 

> I don't consider searching for an nonexistent item an error

That's not quite what I think. I'll amend to:

I consider searching for a nonexistent item an occurrence that the implementation should expect to routinely happen -- in a language with exceptions, for example, I would not recommend the use of an exception for this. However, I'll refrain from commenting on whether this should be represented in JSON as a `-1` sentinel or an `error` object or `null`.

**Comment by petertseng** [comment]
EBWODP:


If this discussion starts to veer too far into "is X an error or not" as opposed to "is this a non-standard error indicator" (the focus of this issue), please ask me to move my comments on "is X an error or not" into a separate issue, keeping this issue focused.

**Comment by petertseng** [comment]
I have decided to move it into a separate issue, keeping this issue focused.

**Comment by rpottsoh** [comment]
binary and trinary  are deprecated, still should be considered?

**Comment by ErikSchierboom** [comment]
> binary and trinary are deprecated, still should be considered?

I wouldn't mind them not having been updated to be honest. As they are deprecated, generators should be ignoring them I think.

**Comment by rpottsoh** [comment]
My pleasure, sorry again about #1337.

**Comment by rpottsoh** [comment]
Should `trinary` and `binary` be stricken from the list above since they are deprecated?

**Comment by ErikSchierboom** [comment]
> Should trinary and binary be stricken from the list above since they are deprecated?

I would be fine with that.

Thanks for doing these @rpottsoh!
