### ISSUE TITLE
Order of canonical-data keys

### ISSUE THREAD

**Issue by SaschaMann** [exercism/problem-specifications#1705]
From @ee7 in https://github.com/exercism/problem-specifications/pull/1703#pullrequestreview-507842858

> But two questions:
> 
>  1. Do we have an official ordering that the keys are supposed to be in?
> 
>  2. If so, should we enforce the key order during CI? Maybe it helps with readability when adding tests. The ordering seemed pretty consistent before, but  there will be nearly double the number of keys now.
> 
> 
> I notice that the `reimplements` in this PR is after `uuid`, but when I made my recent PRs I instead ordered the keys as I saw them in #1674, that is:
> 
> ```json
>   {
>     "uuid": "82d32c2e-07b5-42d9-9b1c-19af72bae860",
>     "description": "two times one is two",
>     "comments": ["Expected value is changed to 2"],
>     "reimplements": "e46c542b-31fc-4506-bcae-6b62b3268537",
>     "property": "twice",
>     "input": {
>       "number": 1
>     },
>     "expected": 2
>   }
> ```

---

## Tasks:

- [ ] Decide if there should be an order
- [ ] Decide on an order
- [ ] Convert all data to the right order
- [ ] Add a CI check for it

**Comment by ErikSchierboom** [comment]
I think the order for virtually all of the existing canonical data is:

1. "uuid"
1. "description"
1. "comments"
1. "property"
1. "input"
1. "expected"

I'm fine with keeping this as is. Maybe we should add the "reimplements" key directly after the "uuid" key?

1. "uuid"
1. "reimplements"
1. "description"
1. "comments"
1. "property"
1. "input"
1. "expected"

**Comment by SaschaMann** [comment]
> Maybe we should add the "reimplements" key directly after the "uuid" key?

I'd like that because it keeps the unreadable part away from the rest

**Comment by ee7** [comment]
@ErikSchierboom And `"scenarios"`? In #1674 it was written last in:
```json
{
  "uuid": "25a8463d-560f-4a42-9be7-b79d00cd28a4",
  "description": "64",
  "property": "square",
  "input": {
    "square": 64
  },
  "expected": 9223372036854775808,
  "scenarios": ["big-integers"]
}
```

**Comment by ErikSchierboom** [comment]
Ah, yes, forgot about that 🤦 Scenarios is basically metadata, so it would perhaps make sense to group it with the other metadata. Maybe:

1. "uuid"
1. "reimplements"
1. "scenarios"
1. "description"
1. "comments"
1. "property"
1. "input"
1. "expected"

or 

1. "uuid"
1. "reimplements"
1. "description"
1. "comments"
1. "scenarios"
1. "property"
1. "input"
1. "expected"

I think I have a slight preference for the latter.

**Comment by iHiD** [comment]
I prefer later but not hard preference.

**Comment by SleeplessByte** [comment]
I prefer the latter too.

**Comment by ErikSchierboom** [comment]
Okay, lets go the following then:

1. "uuid"
1. "reimplements"
1. "description"
1. "comments"
1. "scenarios"
1. "property"
1. "input"
1. "expected"

**Comment by cmccandless** [comment]
Wouldn't this be a change to `configlet fmt`?

**Comment by ErikSchierboom** [comment]
It would, but we're right in the middle of migrating configlet which could take a while.
